---
title: 'Electric Power Consumption in Households'
author: "L.P."
date: "02/01/2016"
output: pdf_document
---

## 1. Alternative Energy: a Solar PV Example

Any alternative energy generation faces difficulties connected with the storage of energy
when there is a surplus in energy generation and release of energy (upond demand) when there is a deficit
in energy generation. 
One example of alternative energy is a solar photovoltaic (PV) system.
It faces challenges including rapid output variations (cloudy vs. sunny), 
daily variability of the output (including seasonal effects), 
effects on power quality (impact on voltage), mismatch between PV output and end-user's peak demand.
Many solutions have been proposed, including storing energy in lithium-ion batteries.
Discussions about how much battery storage does a solar PV system need are ongoing. 
A typical household demand in Europe and US is $5$ to $23$ Wh per minute
(*http://euanmearns.com/how-much-battery-storage-does-a-solar-pv-system-need/*,
*http://shrinkthatfootprint.com/average-household-electricity-consumption*).
Current technologies and research focus on finding solutions how to inegrate
alternative energies, such as the solar PV system, into existing electric grids
(*http://energystorage.org/energy-storage/technology-applications/distributed-grid-connected-pv-integration*).

## 2. Active Power, Reactive Power and Shift Factor

What is electric power?
"Power in an electric circuit is the rate of energy consumption or production as currents flow through various parts 
comprising the circuit.
In alternating current circuits, immediate power transferred through any phase varies periodically. 
Energy storage elements such as inductors and capacitors may result in periodic reversals of the direction of energy flow. 
The portion of power that, averaged over a complete cycle of the AC waveform, results in net transfer of energy in one direction
is known as **active power**. 
The portion of power due to stored energy, which returns to the source in each cycle, is known as **reactive power**."
(https://en.wikipedia.org/wiki/AC_power)

The apparent power is a (vector) sum of active and reactive powers. Ratio of the active to the magnitude of apparent power 
is often called shift factor. **Shift factor** requirements are in place as part of 
existing reactive power standards, typically ranging around $0.95$ lag to lead.
"Voltage on the North American bulk system is normally regulated by Generator Operators, which typically are
provided with voltage schedules by Transmission System operators. In the past, variable generation plants were
considered very small relative to conventional generating units, and were characteristically either induction generator
(wind) or line-commutated inverters (PV) that have no inherent voltage regulation capability. Bulk system voltage
regulation was provided almost exclusively by synchronous generators. 
However, the growing level of penetration of nontraditional renewable generation – especially wind and solar –
has led to the need for renewable generation to contribute more significantly to power system voltage and reactive regulation."
(*http://energy.sandia.gov/energy/renewable-energy/solar-energy/photovoltaics/pv-resources/publications/, A. Ellis et al.: Reactive Power Performance Requirements for Wind and Solar Plants, IEEE PVSC Conf,
Reactive Power Interconnection Requirements for PV and Wind Plants Recommendations to NERC, SAND Report 2012-1098*)
<!-- "As the penetration of renewable resources have grown beyond insignificance, it is now the trend that
variable generators connected to transmission and sub-transmission grids should be required to provide reactive power
support." (*A.Ellis et al., Review of Existing Reactive Power Requirements for Variable Generation, IEEE PVSC Conf*) -->
As a result, companies are now starting to offer innovative products for solar PV systems,
which are designed for producing controlled reactive power. 
(*http://www.sma.de/en/partners/knowledgebase/sma-shifts-the-phase.html*)

## 3. Household Analysis
Our goal is to analyze energy demands and energy flows in households, 
ideally comparing households with and households without installed solar PV systems.
Households represent one group of electric energy end-users. 
Significant factors in household analysis may include: geographic location, region, type of heating/cooling system, 
work-family life style, economic factors.

As a starting point, we study energy demands in a single household
(*https://archive.ics.uci.edu/ml/datasets/Individual+household+electric+power+consumption*).
We look at measurements of electric power consumption with a one-minute sampling rate over a period of almost 4 years,
spanning from 2006-12-16 to 2010-11-26.
```{r, echo=FALSE, message=FALSE, cache=TRUE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(reshape2)
library(scales)
# Multiple plot function:
# http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
        library(grid)
        plots <- c(list(...), plotlist)
        numPlots = length(plots)
        if (is.null(layout)) {
                # Make the panel
                # ncol: Number of columns of plots
                # nrow: Number of rows needed, calculated from # of cols
                layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                                 ncol = cols, nrow = ceiling(numPlots/cols))
        }
        if (numPlots==1) {
                print(plots[[1]])
        } else {
                grid.newpage()
                pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
                
                for (i in 1:numPlots) {
                        # Get the i,j matrix positions of the regions that contain this subplot
                        matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
                        
                        print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                                        layout.pos.col = matchidx$col))
                }
        }
}
household_df <- read.table("../data/household_power_consumption.txt", 
                        header = TRUE,
                        sep = ";",
                        na.strings = c("\\N","","NA","?"),
                        colClasses = c("character",
                                       "character",
                                       "numeric",
                                       "numeric",
                                       "numeric",
                                       "numeric",
                                       "numeric",
                                       "numeric",
                                       "numeric"
                                       ),
                        col.names = c("date",
                                      "time",
                                      "active_power",
                                      "reactive_power",
                                      "voltage",
                                      "intensity",
                                      "sub1",
                                      "sub2",
                                      "sub3"
                                      )
)
household_df$datetime <- as.POSIXct( strptime( paste( household_df$date, household_df$time ), "%d/%m/%Y %H:%M:%S" ) )
## Cleaning Data
recorded_df <- household_df[ complete.cases(household_df), ]
# Calculating submetering not measured in sub1, sub2 or sub3 in Watt-hour
recorded_df$subrest <- (recorded_df$active_power*1000.0/60.0) - recorded_df$sub1 - recorded_df$sub2 - recorded_df$sub3
# Quarter of the measurement: Jan-March == 1, Apr-June == 2, July-Sept == 3, Oct-Dec == 4
recorded_df$quarter <- as.factor(quarter(recorded_df$datetime))
# Setting an arbitrary date for Monday in an average week
recorded_df$time2000 <- update( recorded_df$datetime, year = 2016, month = 02, day = 01, tz = "UTC")
# Calculating apparent power from the active and reactive powers
recorded_df$apparent_power <- sqrt(recorded_df$active_power^2+recorded_df$reactive_power^2)
# Calculating shift factor from the active and apparent powers
recorded_df$shift_factor <- recorded_df$active_power/recorded_df$apparent_power
## Dividing data into Mondays - Sundays by a day attribute, binding them to week
recorded <- tbl_df(recorded_df)
Mondays <- recorded %>% filter( weekdays(datetime) == "Monday" ) %>%
        mutate( time2000 = update( time2000, day = 01 ) )
Tuesdays <- recorded %>% filter( weekdays(datetime) == "Tuesday" ) %>%
        mutate( time2000 = update( time2000, day = 02 ) )
Wednesdays <- recorded %>% filter( weekdays(datetime) == "Wednesday" ) %>%
        mutate( time2000 = update( time2000, day = 03 ) )
Thursdays <- recorded %>% filter( weekdays(datetime) == "Thursday" ) %>%
        mutate( time2000 = update( time2000, day = 04 ) )
Fridays <- recorded %>% filter( weekdays(datetime) == "Friday" ) %>%
        mutate( time2000 = update( time2000, day = 05 ) )
Saturdays <- recorded %>% filter( weekdays(datetime) == "Saturday" ) %>%
        mutate( time2000 = update( time2000, day = 06 ) )
Sundays <- recorded %>% filter( weekdays(datetime) == "Sunday" ) %>%
        mutate( time2000 = update( time2000, day = 07 ) )
week <- rbind( Mondays, Tuesdays, Wednesdays, Thursdays, Fridays, Saturdays, Sundays )
# tick-marks for date axis: from 00:00 Monday to 24:00 Sunday
datebreaks <- seq(as.POSIXct(min(week$time2000)), as.POSIXct("2016-02-08 00:00:00"), by="12 hours")

## Active energy for an average week
aveweek <- week %>% 
        group_by( time2000 ) %>%
        summarize(  active_energy = mean(active_power*1000.0/60.0), 
                sub1 = mean(sub1),
                sub2 = mean(sub2),
                sub3 = mean(sub3),
                subrest = mean(subrest)
        )
names(aveweek) <- c("time2000", "Active Energy", "Kitchen", "Laundry Room", "Water-Heat, AC", "Rest")
aveweekmelt <- melt(aveweek, id="time2000")
p1 <- ggplot(data=aveweekmelt, 
             aes(x=time2000, y=value, colour=variable)) +
        geom_line() +
        scale_colour_manual( name="", values = c("black", "green", "red", "magenta", "blue") ) +
        scale_x_datetime( breaks = datebreaks,
                          labels=date_format("%H:%M"), 
                          limits=c( min(aveweek$time2000), max(aveweek$time2000) ) ) +
        labs( x = "Time [h]: 00:00 Monday through 24:00 Sunday", y = "Active Energy [Wh]", 
              title = "Submetering of Global Active Energy for an Average Week" ) +
        theme( plot.title = element_text(size = rel(1.8), face = "bold"),
                axis.text.x = element_text(size = rel(1.4)),
                axis.title.x = element_text(size = rel(1.6)), 
                axis.text.y = element_text(size = rel(1.3), angle = 90),
                axis.title.y = element_text(size = rel(1.6), angle = 90),
                legend.text = element_text(size = rel(1.0), angle = 45)
        )

## Reactive energy for an average week, compared to kitchen submetering
aveweekr <- week %>% 
        group_by( time2000 ) %>%
        summarize( sub1 = mean(sub1),
                reactive_energy = mean(reactive_power*1000.0/60.0)
        )
names(aveweekr) <- c("time2000","Kitchen", "Reactive Energy")
aveweekrmelt <- melt(aveweekr, id="time2000")
p7 <- ggplot(data=aveweekrmelt, 
             aes(x=time2000, y=value, colour = variable)) +
        geom_line() +
        scale_colour_manual( name="", values = c("lightblue", "black") ) +
        scale_x_datetime( breaks = datebreaks,
                          labels=date_format("%H:%M"), 
                          limits=c( min(aveweekr$time2000), max(aveweekr$time2000) ) ) +
        labs( x = "Time [h]: 00:00 Monday through 24:00 Sunday", y = "Global Reactive Energy [Wh]", 
              title = "Global Reactive Energy for an Average Week" ) +
        theme( plot.title = element_text(size = rel(2), face = "bold"),
                axis.text.x = element_text(size = rel(1.4)),
                axis.title.x = element_text(size = rel(1.6)), 
                axis.text.y = element_text(size = rel(1.3), angle = 90),
                axis.title.y = element_text(size = rel(1.6), angle = 90),
                legend.text = element_text(size = rel(1.1), angle = 45)
        )
## Active and reactive energy by quarters
endweek <- rbind( Thursdays, Fridays, Saturdays, Sundays )
# tick-marks for date axis: from 00:00 Thursday to 24:00 Sunday (UTC vs EST shift)
datebreaks2 <- seq(as.POSIXct("2016-02-03 19:00:00 UTC"), as.POSIXct("2016-02-08 00:00:00 UTC"), by="12 hours")
aveweekq <- endweek %>% 
        group_by( time2000, quarter ) %>%
        summarize( active_energy = mean(active_power*1000.0/60.0), 
                reactive_energy = mean(reactive_power*1000.0/60.0),
                sub1 = mean(sub1),
                sub2 = mean(sub2),
                sub3 = mean(sub3),
                subrest = mean(subrest)
        )
names(aveweekq) <- c("time2000", "quarter", "Active Energy", "Reactive Energy", "Kitchen", "Laundry Room", "Water-Heat, AC", "Rest")
aveweekqmelt <- melt(aveweekq, id=c("time2000","quarter")) 
p3 <- ggplot(data=aveweekqmelt, 
             aes(x=time2000, y=value, colour=variable)) +
        geom_line() +
        facet_grid(quarter~.) +
        scale_colour_manual( name="", values = c("black", "grey", "green", "red", "magenta", "blue") ) +
        scale_x_datetime( breaks = datebreaks2, 
                          labels=date_format("%H:%M"),
                          limits=c( min(aveweekq$time2000), max(aveweekq$time2000) ) ) +
        labs( x = "Time [h]: 00:00 Thursday through 24:00 Sunday", y = "Global Active/Reactive Energy [Wh]", 
              title = "Global Energy by Quarters" ) +
        theme( plot.title = element_text(size = rel(2), face = "bold"),
                axis.text.x = element_text(size = rel(1.4)),
                axis.title.x = element_text(size = rel(1.6)), 
                axis.text.y = element_text(size = rel(1.3), angle = 90),
                axis.title.y = element_text(size = rel(1.6), angle = 90),
                legend.text = element_text(size = rel(1.1), angle = 45)
        )
```

We observe that the average energy consumption in this household is
`r round(mean(recorded_df$active_power)*1000/60.0)` Wh per minute,
with a variability due to seasons:
`r round(mean(recorded_df[recorded_df$quarter==1,]$active_power)*1000/60.0)` Wh per minute during January-March (1st quarter),
`r round(mean(recorded_df[recorded_df$quarter==2,]$active_power)*1000/60.0)` Wh per minute during April-June (2nd quarter),
`r round(mean(recorded_df[recorded_df$quarter==3,]$active_power)*1000/60.0)` Wh per minute during July-September (3rd quarter),
`r round(mean(recorded_df[recorded_df$quarter==4,]$active_power)*1000/60.0)` Wh per minute during October-December (4th quarter).
**Figure 2** shows the global active energy (black curve), its components and small global reactive energy (grey curve) 
for all four quarters, 
from Thursday morning until Sunday evening, on average.
Notice that quarters here do not match the four seasons, however, we can see the seasonal variability in energy demand:
3rd quarter (mostly summer) demands only two thirds of average electric consumption, whereas 
1st and 4th quarters (mostly winter and late/early Fall/Spring, resp.) demand about one fourth of 
electric energy consumption more than on average.

**Figure 1, top panel** shows submetering of global active energy for an average week.
We see an increase in the global active energy (black curve) during the weekend, as opposed to a workday. 
On average, the active energy consumption is 
`r round(mean(recorded_df[weekdays(recorded_df$datetime)=="Saturday" | weekdays(recorded_df$datetime)=="Sunday",]$active_power)*1000/60.0)` Wh per minute during weekends and 
`r round(mean(recorded_df[weekdays(recorded_df$datetime)!="Saturday" & weekdays(recorded_df$datetime)!="Sunday",]$active_power)*1000/60.0)` Wh per minute during weekdays.
In addition, we observe two in demand peaks, one morning peak between 6-9 am, 
and one afternoon peak between 6-9pm, with the weekend data showing more energy demand during afternoon/evening hours.
The water-heat and AC submetering profile (magenta) follows the global active energy profile closely, 
suggesting that a large portion of the energy consumption variance can be explained by water-heat/AC appliances.
Kitchen (greeen) and laundry room (red) appliances, 
including dishwasher, oven, microwave, washing-machine, tumble-drier, refrigerator and light,
represent about `r round(mean((recorded_df$sub1+recorded_df$sub2)/(recorded_df$active_power*1000/60.0))*100.0)`%
of the global active energy,
whereas the water-heat/AC represents about `r round(mean((recorded_df$sub3)/(recorded_df$active_power*1000/60.0))*100.0)`%
of the global active energy.
Interesting contribution, about `r round(mean((recorded_df$subrest)/(recorded_df$active_power*1000/60.0))*100.0)`%,
comes from the so called "rest" energy. Unfortunatelly, this dataset does not specify appliances connected with this
high energy demand (we could speculate that significant portion comes from an electrical heating system, or similar).
Also notice that this household did most of their laundry in the middle of the week (mostly Wednesdays, some Tuesdays)
and during the weekend.

We are also interested in looking at the reactive energy. As seen in figure 2, the amount of reactive energy is small
compared to the active energy.
The average shift factor, ratio of the active energy to the magnitude of the sum of the active and reactive energies is
`r round(mean(recorded_df$shift_factor),2)`.
Its variability due to seasons is the following:
`r round(mean(recorded_df[recorded_df$quarter==1,]$shift_factor),2)` during January-March (1st quarter),
`r round(mean(recorded_df[recorded_df$quarter==2,]$shift_factor),2)` during April-June (2nd quarter),
`r round(mean(recorded_df[recorded_df$quarter==3,]$shift_factor),2)` during July-September (3rd quarter) and
`r round(mean(recorded_df[recorded_df$quarter==4,]$shift_factor),2)` during October-December (4th quarter).
**Figure 1, bottom panel** shows the averaged global reactive energy (black) as a function of time for an average week.
We see that the reactive energy increases during weekends,
and has "afternoon peaks" around 7pm during weekdays.
We also plot the kitchen active energy (light blue) underneath, and compare the reactive and kitchen active energies.
We observe somewhat a similar shape; the afternoon reactive energy peaks could be explained by a correlation
with kitchen active energy, possibly also with laundry room energy (further inference investigation is needed).

In summary, this household data shows 18 Wh per minute average active electric energy consumption,
with a seasonal minumum and maximum of 12 and 22 Wh per minute, respectively.
The variation in the active energy is 21 Wh per minute and 17 Wh per minute during weekends and weekdays, respectively.
The global reactive energy is small, leading to average shift factor of 0.96.







